language: ruby

before_install:
  - mysql -e 'create database datamapper_default_tests;'
  - psql -c 'create database datamapper_default_tests;' -U postgres

bundler_args: --without quality

gemfile:
  - gemfiles/Gemfile.activesupport
  - gemfiles/Gemfile.extlib

env:
  - ADAPTER=sqlite
  - ADAPTER=postgres
  - ADAPTER=mysql

rvm:
  - 1.9.3
  - 1.8.7
