# Generated by Hoe (rake debug_gem)
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name    = "dm-is-slug"
  s.version = "0.9.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors     = ["Aaron Qian", "Nik Radford"]
  s.date        = "2008-12-27"
  s.description = %q{}
  s.email       = [
    "aaron [a] ekohe [d] com",
    "nik [a] terminaldischarge [d] net"
  ]
  s.extra_rdoc_files = ["README.txt"]
  s.files = [
    "History.txt",
    "LICENSE",
    "Manifest.txt",
    "README.txt",
    "Rakefile",
    "TODO",
    "lib/dm-is-slug.rb",
    "lib/dm-is-slug/is/slug.rb",
    "lib/dm-is-slug/is/version.rb",
    "spec/integration/slug_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.has_rdoc          = true
  s.homepage          = "DataMapper plugin for creating and slugs(permalinks)."
  s.rdoc_options      = ["--main", "README.txt"]
  s.require_paths     = ["lib"]
  s.rubyforge_project = "dm-is-slug"
  s.rubygems_version  = "1.3.1"
  s.summary           = %q{}

  if s.respond_to?(:specification_version)
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 2

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<hoe>, [">= 1.8.2"])
    else
      s.add_dependency(%q<hoe>, [">= 1.8.2"])
    end
  else
    s.add_dependency(%q<hoe>, [">= 1.8.2"])
  end
end
